# Exploração

In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

import pandas as pd

from assistente.corpus import REGRA_CONTAGEM_PALAVRAS, carregar_documentos, tabela_palavras

PASTA_INSUMOS = Path.cwd().parent / "data"
pd.set_option("display.max_colwidth", 120)

## Parte 0: Setup e leitura do corpus

Se algo estiver errado nos insumos, a célula abaixo para com `ValueError` explicando o quê.

In [2]:
documentos = carregar_documentos(PASTA_INSUMOS)
documentos[["doc_id", "titulo", "status", "arquivo"]]

,doc_id,titulo,status,arquivo
0,POL-001,Política de Onboarding,vigente,POL-001_onboarding.md
1,POL-002,Política de Férias,vigente,POL-002_ferias.md
2,POL-003,Política de Benefícios,vigente,POL-003_beneficios.md
3,POL-004,Política de Home Office (versão 1),revogada,POL-004_home_office_v1_REVOGADA.md
4,POL-005,Política de Trabalho Híbrido (versão 2),vigente,POL-005_trabalho_hibrido_v2.md
5,POL-006,Política de Reembolso de Despesas,vigente,POL-006_reembolso.md
6,POL-007,Política de Avaliação de Desempenho,vigente,POL-007_avaliacao_desempenho.md
7,POL-008,Política de Desligamento,vigente,POL-008_desligamento.md
8,POL-009,Política de Segurança da Informação,vigente,POL-009_seguranca_informacao.md
9,POL-010,Política de Treinamento e Desenvolvimento,vigente,POL-010_treinamento.md
10,POL-011,Código de Conduta e Canal de Denúncias,vigente,POL-011_codigo_conduta.md
11,FAQ-001,Perguntas Frequentes de Novos Colaboradores,vigente,FAQ-001_perguntas_frequentes.md

Esperado: 11 `vigente` e 1 `revogada` (POL-004).

In [3]:
documentos["status"].value_counts()

status
vigente     11
revogada     1
Name: count, dtype: int64

Evidência da Parte 0 (vai para o `saidas.md`):

In [4]:
print(REGRA_CONTAGEM_PALAVRAS)
tabela_palavras(documentos)

Número de palavras = tokens separados por espaço em branco (`len(texto.split())`) no arquivo completo, incluindo título, cabeçalho `Empresa:` e títulos de seção.

     doc_id    status  palavras
0   POL-001   vigente       164
1   POL-002   vigente       136
2   POL-003   vigente       128
3   POL-004  revogada        90
4   POL-005   vigente       119
5   POL-006   vigente       117
6   POL-007   vigente       114
7   POL-008   vigente       119
8   POL-009   vigente       142
9   POL-010   vigente        92
10  POL-011   vigente       102
11  FAQ-001   vigente       145

Texto completo de um documento, como ficou guardado na coluna `texto` (troque o `doc_id` à vontade):

In [5]:
print(documentos.set_index("doc_id").loc["POL-004", "texto"])

# POL-004 Política de Home Office (versão 1)
Empresa: Horizonte Tech Ltda. (empresa fictícia) | Área responsável: Pessoas e Cultura | Vigência: 01/03/2024 a 31/12/2025 | Versão: 1.0 | Status: revogada (substituída pela POL-005)

## Regra de trabalho remoto
O colaborador pode trabalhar de forma remota em até 2 dias por semana. Os dias remotos são combinados com o gestor direto.

## Auxílio
Não há auxílio financeiro para trabalho remoto nesta versão da política.

## Equipamento
A empresa fornece apenas o notebook corporativo. Outros equipamentos são de responsabilidade do colaborador.